//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestAcaLib.Entities
{
    using System;

    public partial class Absence
	{
		public DateTime Date
		{
			get;
			set;
		}

        public int Id
		{
			get;
			set;
		}
    }
}

