//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestAcaLib.Entities
{
    using System.Collections.Generic;

    public partial class Teacher : Person
	{
        

        public string Ssn
		{
			get;
			set;
		}

		public virtual ICollection<TaughtCourse> TaughtCourses
		{
			get;
			set;
		}
    }
}

